name: Sync github-release → opcUaPlc

on:
  push:
    branches: [ github-release ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Gitea repo
      uses: actions/checkout@v4
      with:
        ref: github-release
        fetch-depth: 0

    - name: Exclude Gitea workflows
      run: |
        git rm -r --cached .gitea/workflows || true
        git rm -r --cached opcUaConfig/opcUaConfig.json || true
        git clean -fd .gitea/workflows || true  # Non tracciati        
        git clean -fd opcUaConfig/opcUaConfig.json || true # Non tracciati  

    - name: Sync to GitHub
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_REPO: ${{ secrets.GH_REPO_OPCUAPLC }}
      run: |
        git config --global user.name "Gitea Action"
        git config --global user.email "action@gitea.local"
        
        # Aggiungi remote e fetch completo
        git remote add github "https://x-access-token:${GH_TOKEN}@github.com/${GH_REPO_OPCUAPLC}.git"
        git fetch github --all --prune --tags
        
        # Detect branch default
        DEFAULT_BRANCH=$(git symbolic-ref -q refs/remotes/github/HEAD | sed 's@^refs/remotes/github/@@' || echo "main")
        echo "🎯 GitHub branch: $DEFAULT_BRANCH"
        
        # Pulisci working dir (fix errore untracked files)
        git clean -fdx
        git checkout --force -B sync-main github/$DEFAULT_BRANCH
        
        # Merge sicuro
        git merge github-release --no-ff -m "Auto-sync Gitea github-release -> $DEFAULT_BRANCH $(date)"
        
        # Push
        git push github sync-main:$DEFAULT_BRANCH --force-with-lease
        
        echo "✅ Completato!"
        git remote remove github
