name: Sync github-release → opcUaPlc main (no workflows)

on:
  push:
    branches: [ github-release ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Gitea repo
      uses: actions/checkout@v4
      with:
        ref: github-release
        fetch-depth: 0

    - name: Exclude Gitea workflows
      run: |
        # Rimuovi solo cartella .gitea/workflows dal staging/index
        git rm -r --cached .gitea/workflows || true
        git rm -r --cached opcUaConfig/opcUaConfig.json
        git clean -fd .gitea/workflows || true  # Non tracciati

    - name: Sync to GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_REPO: ${{ secrets.GH_REPO_OPCUAPLC }}
      run: |
        git config --global user.name "Gitea Action"
        git config --global user.email "action@gitea.local"
        
        git remote add github "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git"
        git fetch github
        
        git checkout -b sync-main github/main
        
        # Merge escludendo .gitea/ (non nel nuovo branch)
        if git merge github-release --no-ff -m "Auto-merge Gitea github-release $(date)"; then
          # Push solo cambiamenti non-.gitea
          git push github sync-main:main --force-with-lease
          echo "✅ Sync su GitHub main (senza .gitea/workflows)"
        else
          echo "❌ Conflict, risolvi manual"
          exit 1
        fi
        
        git remote remove github
        git branch -D sync-main
